# Progetto Vendite
## Fasi del progetto
-  Gestione librerie
-  Importare dati e dataframe
-  Analisi esplorativa e descrittiva
-  Codifica dei dati
    - Uniformato il tipo di dati
    - Uniformato il contenuto dei dati
- Creazione nuove colonne
- Analisi riassuntiva
- Tabelle pivot
- Report Excel
- Prompt AI
- Documento Word con dati e analisi predittiva

## Gestione librerie

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pandasai import SmartDataframe
from pandasai.llm.openai import OpenAI
from docx import Document
from docx.shared import Pt

## Importo dataframe

In [ ]:
df_vendite=pd.read_csv('vendite.csv', sep=';')

In [ ]:
df_vendite.head(5)

         data      cliente    città      prodotto  quantità prezzo_unitario
0  01/01/2024  Cliente 013   Torino  Prodotto 004         6          172,44
1  01/01/2024  Cliente 036  Palermo  Prodotto 047         9             296
2  01/01/2024  Cliente 040     Bari  Prodotto 012         5           41,37
3  01/01/2024  Cliente 030  Potenza  Prodotto 031         9          287,94
4  01/01/2024  Cliente 032  Perugia  Prodotto 056         5            42,1

In [ ]:
df_vendite.tail(5)

,data,cliente,città,prodotto,quantità,prezzo_unitario
99995,30/09/2026,Cliente 047,Milano,Prodotto 044,7,"232,07"
99996,30/09/2026,Cliente 004,Trieste,Prodotto 093,8,"239,33"
99997,30/09/2026,Cliente 039,Cagliari,Prodotto 065,1,"162,66"
99998,30/09/2026,Cliente 011,Napoli,Prodotto 042,7,"152,4"
99999,30/09/2026,Cliente 028,Cagliari,Prodotto 032,8,"334,89"

## Analisi descrittiva

In [ ]:
df_vendite.shape

(100000, 6)

In [ ]:
df_vendite.columns

Index(['data', 'cliente', 'città', 'prodotto', 'quantità', 'prezzo_unitario'], dtype='object')

In [ ]:
df_vendite.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   data             100000 non-null  object
 1   cliente          100000 non-null  object
 2   città            100000 non-null  object
 3   prodotto         100000 non-null  object
 4   quantità         100000 non-null  int64
 5   prezzo_unitario  100000 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB

In [ ]:
df_vendite.describe(include='all')

,data,cliente,città,prodotto,quantità,prezzo_unitario
count,100000,100000,100000,100000,100000.000000,100000
unique,1004,50,20,100,NaN,42660
top,28/05/2024,Cliente 023,Bari,Prodotto 056,NaN,"96,27"
freq,133,2095,5098,1074,NaN,11
mean,NaN,NaN,NaN,NaN,5.497660,NaN
std,NaN,NaN,NaN,NaN,2.867308,NaN
min,NaN,NaN,NaN,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,5.000000,NaN
75%,NaN,NaN,NaN,NaN,8.000000,NaN
max,NaN,NaN,NaN,NaN,10.000000,NaN

## Codifica dei dati

### Uniformare il contenuto delle colonne di tipo testo

In [ ]:
colonne_testo = ["cliente", "città", "prodotto"]
for colonna in colonne_testo:
    df_vendite[colonna] = df_vendite[colonna].astype(str).str.strip()
    df_vendite[colonna] = df_vendite[colonna].astype(str).str.lower()

In [ ]:
df_vendite.head(5)

         data      cliente    città      prodotto  quantità prezzo_unitario
0  01/01/2024  cliente 013   torino  prodotto 004         6          172,44
1  01/01/2024  cliente 036  palermo  prodotto 047         9             296
2  01/01/2024  cliente 040     bari  prodotto 012         5           41,37
3  01/01/2024  cliente 030  potenza  prodotto 031         9          287,94
4  01/01/2024  cliente 032  perugia  prodotto 056         5            42,1

### Uniformare il contenuto delle colonne di tipo numero

In [ ]:
df_vendite['prezzo_unitario'] = df_vendite['prezzo_unitario'].str.replace(',', '.')
df_vendite['prezzo_unitario'] = pd.to_numeric(df_vendite['prezzo_unitario'], errors='coerce')

In [ ]:
df_vendite.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   data             100000 non-null  object
 1   cliente          100000 non-null  object
 2   città            100000 non-null  object
 3   prodotto         100000 non-null  object
 4   quantità         100000 non-null  int64
 5   prezzo_unitario  100000 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 4.6+ MB

### Uniformare il contenuto delle colonne di tipo data

In [ ]:
df_vendite['data'] = df_vendite['data'].str.replace('/', '-')
df_vendite['data']=pd.to_datetime(df_vendite['data'], format="%d-%m-%Y", errors='coerce')

In [ ]:
df_vendite.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   data             100000 non-null  datetime64[ns]
 1   cliente          100000 non-null  object
 2   città            100000 non-null  object
 3   prodotto         100000 non-null  object
 4   quantità         100000 non-null  int64
 5   prezzo_unitario  100000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 4.6+ MB

## Creazione nuove colonne

### Fatturato totale

In [ ]:
df_vendite['fatturato_totale'] = df_vendite['quantità'] * df_vendite['prezzo_unitario']

In [ ]:
df_vendite.head(5)

,data,cliente,città,prodotto,quantità,prezzo_unitario,fatturato_totale
0,2024-01-01,cliente 013,torino,prodotto 004,6,172.44,1034.64
1,2024-01-01,cliente 036,palermo,prodotto 047,9,296.00,2664.00
2,2024-01-01,cliente 040,bari,prodotto 012,5,41.37,206.85
3,2024-01-01,cliente 030,potenza,prodotto 031,9,287.94,2591.46
4,2024-01-01,cliente 032,perugia,prodotto 056,5,42.10,210.50

### Anno

In [ ]:
df_vendite['anno'] = df_vendite['data'].dt.year
df_vendite['anno1'] = df_vendite['data'].dt.to_period('Y')

In [ ]:
df_vendite.head(5)

,data,cliente,città,prodotto,quantità,prezzo_unitario,fatturato_totale,anno,anno1
0,2024-01-01,cliente 013,torino,prodotto 004,6,172.44,1034.64,2024,2024
1,2024-01-01,cliente 036,palermo,prodotto 047,9,296.00,2664.00,2024,2024
2,2024-01-01,cliente 040,bari,prodotto 012,5,41.37,206.85,2024,2024
3,2024-01-01,cliente 030,potenza,prodotto 031,9,287.94,2591.46,2024,2024
4,2024-01-01,cliente 032,perugia,prodotto 056,5,42.10,210.50,2024,2024

### Mese

In [ ]:
df_vendite['mese'] = df_vendite['data'].dt.month
df_vendite['mese1'] = df_vendite['data'].dt.to_period('M')

In [ ]:
df_vendite.head(5)

,data,cliente,città,prodotto,quantità,prezzo_unitario,fatturato_totale,anno,anno1,mese,mese1
0,2024-01-01,cliente 013,torino,prodotto 004,6,172.44,1034.64,2024,2024,1,2024-01
1,2024-01-01,cliente 036,palermo,prodotto 047,9,296.00,2664.00,2024,2024,1,2024-01
2,2024-01-01,cliente 040,bari,prodotto 012,5,41.37,206.85,2024,2024,1,2024-01
3,2024-01-01,cliente 030,potenza,prodotto 031,9,287.94,2591.46,2024,2024,1,2024-01
4,2024-01-01,cliente 032,perugia,prodotto 056,5,42.10,210.50,2024,2024,1,2024-01

## Riepiloghi ed Analisi riassuntive

### Fatturato per prodotto

In [ ]:
fatturato_per_prodotto = df_vendite.groupby('prodotto', as_index=False)['fatturato_totale'].sum().sort_values('fatturato_totale', ascending=False)

In [ ]:
fatturato_per_prodotto

        prodotto  fatturato_totale
21  prodotto 022        1525828.55
36  prodotto 037        1520903.02
31  prodotto 032        1504709.34
71  prodotto 072        1501412.81
80  prodotto 081        1490291.13
..           ...               ...
63  prodotto 064        1304970.37
93  prodotto 094        1304694.99
70  prodotto 071        1304435.22
30  prodotto 031        1291059.96
76  prodotto 077        1289521.83

[100 rows x 2 columns]

### Fatturato per anno

In [ ]:
fatturato_per_anno = df_vendite.groupby(['anno'], as_index=False)['fatturato_totale'].sum().sort_values('anno', ascending=True)

In [ ]:
fatturato_per_anno

   anno  fatturato_totale
0  2024       51173237.36
1  2025       50700146.67
2  2026       38342931.19

### Fatturato per mese-anno

In [ ]:
fatturato_per_mese_anno = df_vendite.groupby(['mese1'], as_index=False)['fatturato_totale'].sum().sort_values('mese1', ascending=True)

In [ ]:
fatturato_per_mese_anno

      mese1  fatturato_totale
0   2024-01        4348337.46
1   2024-02        3951723.54
2   2024-03        4408563.50
3   2024-04        4262801.73
4   2024-05        4134462.55
5   2024-06        4184319.34
6   2024-07        4317089.71
7   2024-08        4385815.31
8   2024-09        4293218.65
9   2024-10        4401089.12
10  2024-11        4216922.25
11  2024-12        4268894.20
12  2025-01        4498381.90
13  2025-02        3941664.87
14  2025-03        4190276.10
15  2025-04        4090343.52
16  2025-05        4190251.07
17  2025-06        4200484.82
18  2025-07        4428130.97
19  2025-08        4386070.54
20  2025-09        4134219.90
21  2025-10        4401520.31
22  2025-11        4070251.33
23  2025-12        4168551.34
24  2026-01        4337778.62
25  2026-02        3811040.75
26  2026-03        4432232.14
27  2026-04        4066974.47
28  2026-05        4411607.89
29  2026-06        4295275.43
30  2026-07        4350993.40
31  2026-08        4549826.01
32  2026-09        4087202.48

### Fatturato per città

In [ ]:
fatturato_per_città = df_vendite.groupby(['città'], as_index=False)['fatturato_totale'].sum().sort_values('fatturato_totale', ascending=False)

In [ ]:
fatturato_per_città

         città  fatturato_totale
6    catanzaro        7244704.39
2         bari        7227428.80
18     trieste        7200660.90
14     potenza        7149763.47
12     palermo        7084383.90
15        roma        7065158.37
17      trento        7054331.53
5   campobasso        7052265.49
1        aosta        7037802.47
7      firenze        6981419.49
19     venezia        6959436.31
16      torino        6957838.86
13     perugia        6955381.97
0       ancona        6951773.23
8       genova        6939301.44
4     cagliari        6938815.43
9     l'aquila        6903794.75
11      napoli        6873343.88
3      bologna        6847098.98
10      milano        6791611.56

### Fatturato per cliente

In [ ]:
fatturato_per_cliente = df_vendite.groupby(['cliente'], as_index=False)['fatturato_totale'].sum().sort_values('fatturato_totale', ascending=False)

In [ ]:
fatturato_per_cliente

        cliente  fatturato_totale
43  cliente 044        2990823.97
25  cliente 026        2970886.21
44  cliente 045        2962222.87
32  cliente 033        2935811.05
19  cliente 020        2931936.20
26  cliente 027        2923179.87
14  cliente 015        2903161.75
22  cliente 023        2900248.83
10  cliente 011        2894053.88
39  cliente 040        2884659.72
16  cliente 017        2884079.94
4   cliente 005        2878425.85
31  cliente 032        2873999.82
21  cliente 022        2869633.00
38  cliente 039        2865284.84
30  cliente 031        2865207.72
37  cliente 038        2859725.72
7   cliente 008        2847651.31
1   cliente 002        2845775.63
0   cliente 001        2845062.65
29  cliente 030        2830674.77
12  cliente 013        2828122.90
40  cliente 041        2810494.83
11  cliente 012        2806281.74
47  cliente 048        2792924.89
6   cliente 007        2789075.75
15  cliente 016        2777512.44
49  cliente 050        2769472.53
42  cliente 043        2768454.54
45  cliente 046        2764371.26
23  cliente 024        2763504.43
3   cliente 004        2752780.89
9   cliente 010        2750514.14
41  cliente 042        2738259.82
17  cliente 018        2736933.91
28  cliente 029        2732674.03
35  cliente 036        2728525.74
24  cliente 025        2723043.50
5   cliente 006        2719947.65
33  cliente 034        2719680.90
27  cliente 028        2716842.37
2   cliente 003        2713573.13
13  cliente 014        2711459.56
18  cliente 019        2706047.32
36  cliente 037        2693114.85
48  cliente 049        2691088.24
34  cliente 035        2689765.33
46  cliente 047        2689722.61
20  cliente 021        2688819.90
8   cliente 009        2680800.42

## Tabelle pivot

### Tabella città prodotto

In [ ]:
pivot_citta_prodotto = pd.pivot_table(
   df_vendite,
   index='città',
   columns='prodotto',
   values='fatturato_totale',
   aggfunc='sum',
   fill_value=0
)

In [ ]:
pivot_citta_prodotto

prodotto,prodotto 001,prodotto 002,prodotto 003,prodotto 004,prodotto 005,prodotto 006,prodotto 007,prodotto 008,prodotto 009,prodotto 010,...,prodotto 091,prodotto 092,prodotto 093,prodotto 094,prodotto 095,prodotto 096,prodotto 097,prodotto 098,prodotto 099,prodotto 100
città,,,,,,,,,,,,,,,,,,,,,
ancona,55659.85,72460.99,83352.50,85359.50,69494.11,64220.24,57551.47,57064.12,63170.55,60113.16,...,88382.94,58891.55,83387.23,81086.19,75218.40,84293.97,64709.05,70523.38,48524.33,59387.90
aosta,76833.28,98434.80,62806.45,96341.01,52974.41,85962.31,76523.38,64929.97,77295.10,69553.82,...,65346.25,69453.50,83474.73,52375.19,83042.40,72558.36,61222.15,63981.98,71691.07,85102.51
bari,89310.58,68740.18,65457.24,88950.62,77246.98,61241.60,71656.36,68560.81,56109.58,76800.29,...,102843.84,66000.50,56274.98,78884.54,83782.73,55983.11,62082.49,66972.06,87532.03,61225.62
bologna,68966.17,97386.37,67264.73,52257.96,78068.74,109052.04,77700.37,73963.42,90240.93,54080.95,...,63901.43,44949.20,100866.47,39671.37,97116.12,69216.39,43839.54,63386.86,74470.42,89678.39
cagliari,56320.11,83123.53,78494.03,85094.52,72275.23,81668.13,67501.73,87275.30,68311.68,69961.95,...,67593.75,59927.91,86980.09,74513.49,56561.02,80319.68,65331.38,49836.07,64557.02,53663.46
campobasso,76280.29,62638.78,77437.02,61269.71,87744.84,60841.31,53450.57,85257.26,69772.49,79992.45,...,81400.14,56243.04,61911.97,58114.15,62019.96,61381.94,63870.08,72747.86,72577.32,58990.26
catanzaro,67602.37,52981.00,56547.49,71502.21,65154.97,65581.50,64800.14,93520.80,90531.09,89077.59,...,74005.02,66546.39,63191.42,62499.70,80600.43,66408.10,70688.23,106071.05,51057.97,67259.50
firenze,68396.75,95416.22,63052.82,56720.22,53363.31,52559.60,59841.64,68610.96,73351.16,76012.76,...,51378.36,60795.12,78354.61,57310.31,73312.13,68566.84,51327.23,75380.35,70222.64,73469.13
genova,69548.77,72131.94,64044.01,55853.90,67947.49,66501.29,78147.15,71753.03,76677.29,62905.97,...,82511.53,85723.27,62382.85,79859.25,76921.53,54191.99,76403.92,73166.56,59379.56,83137.24
l'aquila,68411.11,52515.95,67568.34,83371.29,50198.62,77991.14,53992.81,57849.46,59610.97,60805.72,...,69877.06,75055.90,69229.17,45557.36,66154.35,56951.33,91303.74,65681.90,75970.22,84790.66
milano,54201.82,48095.93,67112.55,63649.77,80709.29,86407.81,64681.03,94798.77,76679.90,63980.26,...,55314.85,72715.47,76180.69,72164.91,75073.62,56361.40,69916.60,72119.64,60335.52,60138.77
napoli,55743.71,64713.14,72181.06,75368.87,53074.33,83374.16,77597.94,72018.62,72857.90,73352.24,...,75999.46,67317.23,63421.14,62228.12,69873.52,54169.40,59951.23,71696.76,96350.28,86725.29
palermo,65812.74,84303.57,101223.51,84140.39,62052.43,68802.52,49842.16,61364.09,68164.44,71669.70,...,85517.41,52508.67,67228.97,57232.98,61689.13,83214.48,76290.87,47037.83,43955.94,82503.74
perugia,75221.50,74800.49,67418.41,71345.42,75773.72,53989.71,54961.07,58930.07,81493.23,77018.03,...,97130.74,72061.28,50903.97,47497.03,64842.89,105237.11,60618.14,55699.10,62818.58,83864.02
potenza,83160.20,68894.64,67059.45,71030.54,74884.61,74863.56,75758.62,43118.53,49658.38,69033.95,...,58820.42,87369.09,64358.52,79939.05,71889.29,83072.61,60708.16,75262.91,40639.33,71339.41
roma,63865.40,76911.69,69709.07,57102.45,63934.97,41572.26,62333.10,57503.49,49731.14,73813.19,...,67331.21,60688.34,87514.81,56097.94,65889.58,68786.58,78655.30,81720.76,94925.71,76565.89
torino,75111.54,71247.68,63070.95,85133.57,87242.89,52807.04,80696.19,76747.18,55025.35,83155.57,...,68694.64,58927.64,46106.30,73174.68,71050.11,62293.17,67124.94,80227.69,74987.81,50376.83
trento,63882.47,72123.35,73933.59,54056.83,69986.44,79152.17,85445.16,82519.51,88927.21,61909.59,...,59707.20,55043.49,77753.57,71329.05,61210.91,64381.42,74894.27,71453.65,92337.48,69166.34
trieste,87863.12,57523.35,79980.54,51274.82,72565.18,56851.36,87258.29,104427.84,74106.49,61825.75,...,91837.13,95180.88,83854.70,71425.82,57588.31,73415.01,79308.28,66090.96,71069.30,81216.59
venezia,56922.17,60698.68,74598.52,82317.55,76529.76,94035.33,71552.48,60499.33,48323.22,59164.80,...,74482.10,63032.68,74065.05,83733.86,82705.38,61194.14,66220.20,61177.08,77727.90,41946.01

### Per città anno

In [ ]:
pivot_citta_anno = pd.pivot_table(
   df_vendite,
   index='città',
   columns='anno',
   values='fatturato_totale',
   aggfunc='sum',
   fill_value=0
)
pivot_citta_anno

anno              2024        2025        2026
città
ancona      2530857.45  2536100.13  1884815.65
aosta       2456006.31  2518942.82  2062853.34
bari        2629291.90  2711997.74  1886139.16
bologna     2525368.17  2441301.74  1880429.07
cagliari    2513112.67  2520103.94  1905598.82
campobasso  2564986.79  2540497.44  1946781.26
catanzaro   2639226.18  2627070.98  1978407.23
firenze     2452150.70  2654786.93  1874481.86
genova      2578912.75  2319513.27  2040875.42
l'aquila    2448047.49  2537698.81  1918048.45
milano      2585581.59  2391370.60  1814659.37
napoli      2599436.07  2456236.09  1817671.72
palermo     2588849.59  2564457.59  1931076.72
perugia     2421510.73  2582338.79  1951532.45
potenza     2493188.39  2597886.99  2058688.09
roma        2652536.41  2597031.93  1815590.03
torino      2493771.48  2578767.36  1885300.02
trento      2547050.51  2563214.58  1944066.44
trieste     2727916.30  2550015.89  1922728.71
venezia     2725435.88  2410813.05  1823187.38

### Per città anno-mese

In [ ]:
pivot_citta_anno_mese = pd.pivot_table(
   df_vendite,
   index='città',
   columns='mese1',
   values='fatturato_totale',
   aggfunc='sum',
   fill_value=0
)
pivot_citta_anno_mese

mese1,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,...,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05,2026-06,2026-07,2026-08,2026-09
città,,,,,,,,,,,,,,,,,,,,,
ancona,178534.12,192474.06,213095.49,232823.42,168668.81,193877.07,252096.23,220909.38,221017.71,223085.11,...,189590.81,213417.87,184017.25,223299.62,198375.29,214192.51,195283.07,223103.69,208162.46,224963.89
aosta,205543.98,176030.93,203145.00,219945.76,201320.52,261413.93,192094.95,193433.92,241332.52,188365.96,...,213922.51,210115.77,239516.88,236645.09,220879.18,221780.52,242585.61,194037.28,292397.48,204895.53
bari,200040.61,243646.19,212644.88,209287.42,215979.18,197617.24,196042.12,228266.81,281773.95,192070.15,...,248022.83,220124.87,207897.05,235571.39,202413.62,211001.50,225021.50,189547.74,228402.17,166159.32
bologna,232455.73,200101.49,221760.72,230549.55,188827.51,203164.02,187165.03,209395.33,212497.95,194784.75,...,217688.65,225372.16,195195.03,171839.85,241779.92,242173.05,203197.41,224680.75,205311.47,170879.43
cagliari,235636.60,188818.24,223125.38,167369.78,197021.40,232148.55,224419.57,203692.57,219680.90,216752.59,...,186895.56,208132.29,187246.31,194324.73,177862.59,246766.44,252788.69,190110.76,197293.66,251073.35
campobasso,207693.33,187954.18,216837.80,225628.57,211735.60,249634.35,192522.47,227629.09,161901.57,236547.97,...,221038.74,216999.63,189533.17,229666.69,219616.93,215150.28,227134.80,237584.39,234794.43,176300.94
catanzaro,221737.88,215291.96,213397.16,229016.25,197619.09,219619.18,199427.15,255367.27,237963.66,238814.44,...,182611.20,206679.42,185510.33,236284.30,204091.68,195393.97,242030.11,231248.88,231793.72,245374.82
firenze,197543.01,211129.86,201524.56,214292.80,210785.35,187975.69,195091.19,200288.72,237941.13,233671.81,...,210888.00,187778.63,190240.43,227586.64,222753.68,209194.65,183459.02,203492.31,261323.58,188652.92
genova,233963.03,209362.99,196286.38,218077.26,210786.68,179538.73,213850.47,239333.51,183442.23,211379.33,...,207669.49,203579.14,184638.01,270890.67,215486.72,250446.37,231645.43,222325.64,227216.16,234647.28
l'aquila,233766.67,158733.97,214500.53,190927.96,201773.94,197938.55,242010.81,204322.97,184690.84,227105.40,...,200057.86,212531.46,220134.87,214537.95,180709.54,226120.72,209868.63,213552.18,227332.32,213260.78
milano,222357.03,211295.19,223729.03,209107.72,220478.16,187057.50,244220.20,211222.94,192371.17,212861.36,...,205063.05,232652.24,166423.55,203022.94,250048.07,172216.21,201040.04,175592.34,215679.63,197984.35
napoli,274610.32,176694.70,205726.61,226794.31,223087.17,212337.19,244265.31,195440.08,200395.76,208506.10,...,238582.32,250946.98,179488.57,193917.70,170691.64,189940.96,198906.51,232783.57,204352.57,196643.22
palermo,209900.68,174608.12,216138.89,241516.80,200488.67,204489.44,217780.75,215108.65,219414.55,235143.19,...,206292.27,219307.27,162524.99,222139.02,231405.14,217798.05,198252.58,240339.50,245067.31,194242.86
perugia,203950.54,204240.16,179894.68,213159.82,232592.63,186351.49,181278.35,180031.60,193058.27,224840.90,...,186125.44,222396.11,160725.09,236707.33,214629.23,221142.15,206942.22,242860.99,246516.59,199612.74
potenza,206020.91,191304.48,192917.75,198537.33,216587.88,190692.96,252412.73,227854.88,206147.36,239561.45,...,222228.12,231910.34,210006.02,243064.64,218292.80,232338.42,181991.45,211439.26,264120.77,265524.39
roma,247257.85,182041.04,234643.48,192722.74,203316.38,212764.39,243083.95,228220.65,250216.64,215549.21,...,222636.63,187125.69,202070.17,217380.35,163839.18,233418.27,193982.33,242443.20,196627.45,178703.39
torino,179461.39,190686.43,254272.50,208889.27,200481.78,239566.13,219526.36,239764.38,194717.62,212444.68,...,194541.06,239454.17,198964.64,189689.05,183135.95,201838.53,244659.76,220616.41,210967.22,195974.29
trento,220253.08,207840.10,252254.05,174563.00,204182.96,212689.16,188838.34,191969.26,204434.72,221091.21,...,219553.33,214598.79,203519.46,235571.18,206768.40,273573.40,226992.64,211623.95,196748.42,174670.20
trieste,229910.74,225684.11,263544.34,230686.02,226337.84,213812.51,213381.91,283337.04,200956.53,215491.95,...,217415.98,198680.13,163979.21,227508.24,189870.15,233492.14,218165.00,226290.34,241427.81,223315.69
venezia,207699.96,203785.34,269124.27,228905.95,202391.00,201631.26,217581.82,230226.26,249263.57,253021.56,...,177727.49,235975.66,179409.72,222584.76,154324.76,203629.75,211328.63,217320.22,214290.79,184323.09

### Per prodotto anno

In [ ]:
pivot_anno_prodotto = pd.pivot_table(
   df_vendite,
   index='anno',
   columns='prodotto',
   values='fatturato_totale',
   aggfunc='sum',
   fill_value=0
)
pivot_anno_prodotto

prodotto,prodotto 001,prodotto 002,prodotto 003,prodotto 004,prodotto 005,prodotto 006,prodotto 007,prodotto 008,prodotto 009,prodotto 010,...,prodotto 091,prodotto 092,prodotto 093,prodotto 094,prodotto 095,prodotto 096,prodotto 097,prodotto 098,prodotto 099,prodotto 100
anno,,,,,,,,,,,,,,,,,,,,,
2024,528509.62,481608.40,568234.15,565704.67,515759.08,502320.84,481317.74,509742.55,536972.29,495386.18,...,507680.17,536881.07,496739.27,465470.67,475610.16,489016.98,472526.73,493679.69,491389.25,535332.67
2025,516126.25,498252.57,508346.80,474119.10,520903.96,517327.08,502118.07,567046.40,486372.79,535739.05,...,517865.45,420974.49,542987.20,446988.35,552588.68,540162.01,525617.30,518919.25,542644.76,475815.44
2026,334478.08,455281.31,345731.33,392317.38,354559.28,397827.16,387855.85,363923.61,366693.02,363102.51,...,456529.86,370575.59,397714.77,392235.97,408342.97,352818.04,346321.77,377635.51,357096.42,409399.45

### Per prodotto anno-mese

In [ ]:
pivot_mese1_prodotto = pd.pivot_table(
   df_vendite,
   index='mese1',
   columns='prodotto',
   values='fatturato_totale',
   aggfunc='sum',
   fill_value=0
)
pivot_mese1_prodotto

prodotto,prodotto 001,prodotto 002,prodotto 003,prodotto 004,prodotto 005,prodotto 006,prodotto 007,prodotto 008,prodotto 009,prodotto 010,...,prodotto 091,prodotto 092,prodotto 093,prodotto 094,prodotto 095,prodotto 096,prodotto 097,prodotto 098,prodotto 099,prodotto 100
mese1,,,,,,,,,,,,,,,,,,,,,
2024-01,20768.61,43762.45,41275.24,62205.88,48970.58,58336.60,41832.00,44233.09,57542.21,45781.51,...,41676.05,52574.57,30756.66,31011.73,31884.77,37206.06,45320.85,44396.47,27636.61,55502.77
2024-02,53507.84,26083.50,45168.49,47359.08,44621.03,49346.14,30112.79,42516.27,48503.80,23140.33,...,34081.76,35542.26,35908.28,33349.33,21224.38,51414.96,33185.62,47654.25,49296.72,42701.53
2024-03,34563.12,39479.42,43499.06,31287.53,37762.05,35149.61,40415.73,24647.03,50998.82,41652.48,...,46402.31,50143.64,46567.64,48914.56,49932.29,36874.39,54587.63,41386.74,38796.22,52033.90
2024-04,43506.76,43425.27,41480.44,36896.90,38244.04,40752.77,43890.89,34437.83,52285.45,54949.70,...,40434.84,24262.04,46602.52,29874.88,50286.54,49062.16,42735.09,20203.32,39660.37,45497.11
2024-05,47627.34,49425.05,53223.44,47255.17,44029.52,44547.00,28818.51,39395.16,52029.67,40586.45,...,51350.41,44149.12,32449.34,37100.89,42697.48,40373.67,15202.26,29763.63,44445.70,28760.55
2024-06,53038.38,29686.75,41930.88,38996.25,52836.08,32210.05,37564.51,49236.62,27254.88,53534.53,...,47960.27,31679.16,47618.31,30838.73,49323.00,32145.97,27925.33,44993.38,28726.30,62383.52
2024-07,41107.75,38965.04,55164.67,69426.80,52234.50,38001.87,46497.45,60468.44,58358.03,45369.18,...,48763.17,55555.38,41845.25,41128.63,38614.19,43243.76,42722.55,38955.62,45481.32,52735.09
2024-08,42082.96,64503.94,56360.66,53440.81,31812.05,37185.41,38200.54,59314.97,42883.30,43945.76,...,35752.54,40780.38,38392.95,24526.14,39966.17,48723.66,40216.97,34630.90,55515.30,48281.45
2024-09,44050.35,26445.74,56247.59,55167.08,46831.48,52598.03,29597.94,29537.21,49132.21,32676.21,...,41619.67,70644.82,49658.67,51168.93,42748.41,47696.41,60939.83,41014.71,42885.99,32018.35
2024-10,45434.08,35994.80,62615.51,26043.74,47891.96,38846.15,53887.72,45634.36,27375.99,33775.95,...,37110.87,49887.15,45754.06,41297.96,33558.44,32072.70,38471.89,43155.18,37687.79,31963.69
2024-11,43492.49,54964.33,47542.81,40269.71,40421.78,43153.91,43829.04,42085.28,29909.17,44337.35,...,40146.88,37606.56,47753.10,54634.39,28409.85,42983.72,33982.29,57481.77,39362.55,42050.79
2024-12,59329.94,28872.11,23725.36,57355.72,30104.01,32193.30,46670.62,38236.29,40698.76,35636.73,...,42381.40,44055.99,33432.49,41624.50,46964.64,27219.52,37236.42,50043.72,41894.38,41403.92
2025-01,59763.74,37552.63,36697.59,40082.23,45650.12,45632.25,58256.01,47330.93,46817.94,47071.37,...,42880.35,24807.92,45119.48,34258.84,46920.04,43332.77,46136.01,49920.22,48203.54,47109.46
2025-02,25956.72,26227.64,28006.45,44523.86,44690.91,44046.11,26859.11,34727.75,53168.37,50159.27,...,40495.83,34314.14,25338.91,38850.78,43031.13,54334.50,47346.10,37671.00,33754.01,50464.21
2025-03,38631.19,35676.24,49453.68,35160.60,49402.72,45491.87,48261.74,45424.26,30780.24,53974.22,...,40558.82,28398.50,46143.55,46204.06,52202.97,40523.53,30585.87,45542.64,30329.36,32526.00
2025-04,37639.74,48970.26,33795.70,47657.19,51848.81,43766.74,42485.34,38815.12,33376.58,48289.25,...,64050.88,32653.28,42286.82,56505.86,33425.42,35813.52,46884.94,38690.31,32380.41,35771.61
2025-05,57808.85,53264.47,60135.25,29115.33,41981.86,43440.55,46445.32,41699.36,39592.13,49707.72,...,44639.51,35732.05,55919.43,39659.10,39242.36,34908.46,44974.04,32507.73,45046.27,34298.36
2025-06,34239.04,52138.90,47992.59,38977.49,36978.19,46451.33,35664.80,27377.57,50763.93,45257.47,...,39710.82,34382.86,36107.94,44951.98,47269.76,31621.10,39342.09,36857.85,60610.32,27633.35
2025-07,37560.71,50902.99,34902.31,51453.78,41496.06,33833.98,40413.09,51346.42,47259.13,44342.69,...,36512.97,40368.56,48137.70,28668.52,65840.06,39981.18,42459.95,49437.39,46884.38,41867.82
2025-08,36557.98,28267.22,37681.94,38823.29,48349.96,48306.13,44995.13,52302.90,37849.77,50039.91,...,47214.97,40122.98,53502.79,21685.27,61656.42,44296.64,36517.28,38254.74,65678.19,45163.30
2025-09,49410.36,57053.38,21525.07,33256.21,32787.53,24527.38,33360.58,38691.81,31511.04,18262.71,...,37731.16,54124.36,54728.42,29924.20,59215.41,41167.89,51771.01,49757.53,36590.94,41458.16
2025-10,32670.10,35734.54,51859.90,40362.82,25845.36,48510.92,50085.45,76480.93,38706.84,40802.46,...,46732.75,42782.14,39425.62,25860.28,21003.54,74438.86,43665.61,49326.41,57191.98,33034.06
2025-11,57251.58,34300.86,46741.57,34419.70,42265.06,57123.97,44417.34,67615.11,41288.79,48436.98,...,32450.76,22562.89,43918.70,27471.93,57066.15,54666.35,47867.05,45575.43,38333.33,50115.89
2025-12,48636.24,38163.44,59554.75,40286.60,59607.38,36195.85,30874.16,45234.24,35258.03,39395.00,...,44886.63,30724.81,52357.84,52947.53,25715.42,45077.21,48067.35,45378.00,47642.03,36373.22
2026-01,44583.86,36799.36,40872.24,32119.61,43008.00,58103.94,60126.35,33484.36,53834.12,46826.50,...,41112.09,40015.34,50504.66,59602.32,46266.74,36127.22,43944.48,50658.60,32988.20,45809.33
2026-02,19829.31,41197.75,28686.81,43030.78,31766.24,51315.98,27556.01,34404.08,44722.03,36003.47,...,39457.52,35895.11,33873.65,24248.87,51172.34,41347.74,31645.07,51304.75,33363.04,46778.03
2026-03,48582.88,58612.84,33826.31,35281.83,58324.71,48928.95,58838.81,45923.16,43913.02,46098.60,...,66749.15,37043.42,41015.30,36369.33,50004.54,41940.49,33351.86,44645.41,48885.15,62852.22
2026-04,28686.17,65054.26,58358.39,59393.49,34593.65,42654.51,32131.27,58128.92,44228.32,33020.94,...,60609.49,44766.49,58583.05,44411.22,43666.75,34713.74,49363.58,37961.08,34954.45,41652.16
2026-05,35647.73,58828.93,34444.82,42563.73,32807.09,30730.49,49634.92,34775.10,33267.67,46305.28,...,67012.96,36669.97,35294.02,43046.16,58721.46,39282.23,41007.57,35402.34,42352.51,63219.98
2026-06,44396.28,48346.37,32356.90,57327.15,39871.43,41713.00,34646.80,49244.36,27888.89,39938.87,...,45352.75,49262.22,43052.13,50787.15,45003.02,42595.88,35831.83,52359.94,48465.46,38905.39
2026-07,34148.40,34696.19,30938.32,28102.96,36907.22,28867.44,56829.34,56582.39,47602.53,45429.32,...,51884.08,30955.79,46194.18,45238.97,42692.95,36346.15,32401.21,38285.79,47465.42,36629.76
2026-08,41041.96,79800.61,49335.01,43017.09,40109.88,47898.37,29059.38,33590.99,52892.15,44846.80,...,41801.26,43420.07,49299.56,58127.65,42787.96,48460.58,43416.36,44853.67,44522.66,34936.06
2026-09,37561.49,31945.00,36912.53,51480.74,37171.06,47614.48,39032.97,17790.25,18344.29,24632.73,...,42550.56,52547.18,39898.22,30404.30,28027.21,32004.01,35359.81,22163.93,24099.53,38616.52

## Report Excel multi-foglio

In [ ]:
nome_report = f"report_vendite_{datetime.now().strftime('%Y%m%d')}.xlsx"

with pd.ExcelWriter(nome_report, engine='openpyxl') as writer:
    df_vendite.to_excel(writer, sheet_name='Dati puliti', index=False)
    fatturato_per_prodotto.to_excel(writer, sheet_name='Per prodotto', index=False)
    fatturato_per_città.to_excel(writer, sheet_name='Per città', index=False)
    fatturato_per_mese_anno.to_excel(writer, sheet_name='Per mese', index=False)
    fatturato_per_anno.to_excel(writer, sheet_name='Per anno', index=False)
    pivot_citta_prodotto.to_excel(writer, sheet_name='Pivot città-prodotto')
    pivot_mese1_prodotto.to_excel(writer, sheet_name='Pivot mese1-prodotto')
    pivot_anno_prodotto.to_excel(writer, sheet_name='Pivot anno-prodotto')
    pivot_citta_anno.to_excel(writer, sheet_name='Pivot città-anno')
    pivot_citta_anno_mese.to_excel(writer, sheet_name='Pivot città-anno-mese')

nome_report

'report_vendite_20261023.xlsx'

## Prompt per l’AI
Usa solo dati aggregati, non i dati grezzi con clienti identificabili:

In [ ]:
totale = df_vendite['fatturato_totale'].sum()

prodotto_top = fatturato_per_prodotto.loc[fatturato_per_prodotto['fatturato_totale'].idxmax(), 'prodotto']
citta_top = fatturato_per_città.loc[fatturato_per_città['fatturato_totale'].idxmax(), 'città']

prompt_ai = f"""
Comportati come un analista dati aziendale.

Analizza i seguenti dati di vendita aggregati.

Fatturato totale: {totale:.2f} euro
Prodotto più redditizio: {prodotto_top}
Città con maggior fatturato: {citta_top}

Dati per prodotto:
{fatturato_per_prodotto.to_string(index=False)}

Dati per città:
{fatturato_per_città.to_string(index=False)}

Dati per mese:
{fatturato_per_mese_anno.to_string(index=False)}

Genera:
1. Tre insight principali.
2. Due rischi o anomalie.
3. Tre azioni commerciali concrete.
4. Una previsione qualitativa per il prossimo periodo.

Usa un linguaggio semplice, professionale e operativo.
"""

print(prompt_ai)

with open('prompt_ai.txt', 'w', encoding='utf-8') as f:
    f.write(prompt_ai)

Comportati come un analista dati aziendale.

Analizza i seguenti dati di vendita aggregati.

Fatturato totale: 140216315.22 euro
Prodotto più redditizio: prodotto 022
Città con maggior fatturato: catanzaro

Dati per prodotto:
    prodotto  fatturato_totale
prodotto 022        1525828.55
prodotto 037        1520903.02
prodotto 032        1504709.34
prodotto 072        1501412.81
prodotto 081        1490291.13
prodotto 055        1487334.02
prodotto 079        1484791.70
prodotto 015        1483131.15
prodotto 091        1482075.48
prodotto 040        1474125.94
prodotto 054        1463732.59
prodotto 059        1462502.44
prodotto 066        1460757.02
prodotto 065        1460452.63
prodotto 045        1456772.42
prodotto 088        1455173.30
prodotto 087        1453487.80
prodotto 051        1451763.66
prodotto 029        1444649.75
prodotto 063        1442613.39
prodotto 056        1442263.13
prodotto 008        1440712.56
prodotto 016        1440138.13
prodotto 084        1439628.07
prodotto 093        1437441.24
prodotto 095        1436541.81
prodotto 002        1435142.28
prodotto 047        1433001.05
prodotto 004        1432141.15
prodotto 073        1431165.65
prodotto 025        1425353.03
prodotto 003        1422312.28
prodotto 100        1420547.56
prodotto 058        1420271.64
prodotto 030        1419777.70
prodotto 006        1417475.08
prodotto 061        1416868.94
prodotto 085        1416737.42
prodotto 067        1416641.64
prodotto 050        1416092.48
prodotto 035        1411758.67
prodotto 083        1411516.46
prodotto 033        1410274.09
prodotto 048        1410198.00
prodotto 080        1409522.94
prodotto 041        1409227.31
prodotto 049        1404438.17
prodotto 074        1404028.72
prodotto 089        1401206.86
prodotto 068        1396889.36
prodotto 070        1395287.62
prodotto 078        1394392.23
prodotto 010        1394227.74
prodotto 038        1394177.67
prodotto 012        1393415.27
prodotto 013        1392056.67
prodotto 023        1391757.73
prodotto 005        1391222.32
prodotto 099        1391130.43
prodotto 053        1390567.44
prodotto 098        1390234.45
prodotto 009        1390038.10
prodotto 017        1387357.55
prodotto 011        1387190.93
prodotto 060        1386868.43
prodotto 069        1386316.61
prodotto 042        1385536.49
prodotto 052        1382581.37
prodotto 096        1381997.03
prodotto 001        1379113.95
prodotto 014        1378251.03
prodotto 046        1378119.19
prodotto 026        1372713.17
prodotto 007        1371291.66
prodotto 028        1365297.46
prodotto 019        1364161.11
prodotto 034        1364069.87
prodotto 076        1361619.81
prodotto 057        1358899.79
prodotto 018        1358842.16
prodotto 075        1358780.37
prodotto 020        1357712.97
prodotto 027        1357188.86
prodotto 090        1352413.20
prodotto 082        1351890.61
prodotto 097        1344465.80
prodotto 036        1342357.40
prodotto 024        1341497.98
prodotto 062        1341139.46
prodotto 086        1335818.97
prodotto 021        1331734.28
prodotto 043        1330561.56
prodotto 092        1328431.15
prodotto 044        1327236.88
prodotto 039        1325846.52
prodotto 064        1304970.37
prodotto 094        1304694.99
prodotto 071        1304435.22
prodotto 031        1291059.96
prodotto 077        1289521.83

Dati per città:
     città  fatturato_totale
 catanzaro        7244704.39
      bari        7227428.80
   trieste        7200660.90
   potenza        7149763.47
   palermo        7084383.90
      roma        7065158.37
    trento        7054331.53
campobasso        7052265.49
     aosta        7037802.47
   firenze        6981419.49
   venezia        6959436.31
    torino        6957838.86
   perugia        6955381.97
    ancona        6951773.23
    genova        6939301.44
  cagliari        6938815.43
  l'aquila        6903794.75
    napoli        6873343.88
   bologna        6847098.98
    milano        6791611.56

Dati per mese:
  mese1  fatturato_totale
2024-01        4348337.46
2024-02        3951723.54
2024-03        4408563.50
2024-04        4262801.73
2024-05        4134462.55
2024-06        4184319.34
2024-07        4317089.71
2024-08        4385815.31
2024-09        4293218.65
2024-10        4401089.12
2024-11        4216922.25
2024-12        4268894.20
2025-01        4498381.90
2025-02        3941664.87
2025-03        4190276.10
2025-04        4090343.52
2025-05        4190251.07
2025-06        4200484.82
2025-07        4428130.97
2025-08        4386070.54
2025-09        4134219.90
2025-10        4401520.31
2025-11        4070251.33
2025-12        4168551.34
2026-01        4337778.62
2026-02        3811040.75
2026-03        4432232.14
2026-04        4066974.47
2026-05        4411607.89
2026-06        4295275.43
2026-07        4350993.40
2026-08        4549826.01
2026-09        4087202.48

Genera:
1. Tre insight principali.
2. Due rischi o anomalie.
3. Tre azioni commerciali concrete.
4. Una previsione qualitativa per il prossimo periodo.

Usa un linguaggio semplice, professionale e operativo.

Il portafoglio è molto bilanciato: nessun prodotto o città concentra il fatturato, quindi il rischio principale non è la dipendenza da pochi prodotti, ma la difficoltà di individuare leve di crescita differenziate. Il fatturato totale è di 140,2 milioni di euro, con un andamento mensile stabile ma una leggera flessione annua nel 2025.

## Tre insight principali

- **Portafoglio prodotti estremamente omogeneo.** Il prodotto 022 guida con 1,53 milioni di euro, ma il divario rispetto all’ultimo prodotto (077) è solo del 18,3%; i primi 10 prodotti generano appena il 10,7% del totale. Questo indica una domanda distribuita, con pochi “campioni” netti da scalare rapidamente.

- **Catanzaro guida, ma le città sono quasi alla pari.** Catanzaro fattura 7,24 milioni, seguita da vicino da Bari e Trieste; Milano è ultima con 6,79 milioni. La forbice tra prima e ultima città è solo del 6,7%, quindi non esistono mercati fortemente sottoperformanti o dominanti.

- **Andamento mensile stabile, con stagionalità marcata a febbraio.** Febbraio è sistematicamente il mese più debole: in media 3,90 milioni contro 4,28 milioni degli altri mesi, cioè circa il 9% in meno. Agosto e ottobre sono invece tra i mesi più solidi, con medie rispettivamente di 4,44 e 4,40 milioni di euro.

## Due rischi o anomalie

- **Flessione del 2025.** Il fatturato 2025 è sceso dello 0,9% rispetto al 2024, passando da 51,17 a 50,70 milioni di euro. Non è un crollo, ma segnala una crescita ferma che merita indagine su prezzi, mix, churn clienti o pressione competitiva.

- **Febbraio ricorrentemente sotto target.** Il calo di febbraio si ripete per tre anni consecutivi, con il minimo assoluto nel 2026 (3,81 milioni). Potrebbe dipendere da stagione, calendario vendite, rinnovi o minore attività commerciale, ma va verificato perché crea un buco prevedibile nel flusso di fatturato.

## Tre azioni commerciali concrete

- **Lanciare una campagna “Febbraio” strutturata.** Attivare promozioni, bundle, incentivi per la forza vendita e campagne di riattivazione clienti già da gennaio, con obiettivo di recuperare almeno metà del gap medio di circa 380 mila euro mensili.

- **Replicare le pratiche di Catanzaro nelle città medie.** Analizzare clienti, canali e prodotti che sostengono Catanzaro, Bari e Trieste, quindi trasferire playbook commerciali mirati a Milano, Bologna e Napoli, che oggi sono le tre città più basse.

- **Creare un programma di crescita per i prodotti 077, 031, 071, 094 e 064.** Sono gli ultimi cinque per fatturato; invece di tagliarli, testare pricing, posizionamento, formazione venditori e offerte mirate per capire se il problema è domanda, visibilità o esecuzione commerciale.

## Previsione qualitativa

Per il prossimo periodo ci si attende una **continuità dei volumi, senza una crescita forte automatica**: i primi nove mesi del 2026 sono leggermente sopra il medesimo periodo del 2025 (+0,7%), ma l’andamento resta piatto.  Se non si interviene su febbraio e sulle città a minore performance, il trimestre in chiusura dovrebbe restare stabile, con ottobre potenzialmente tra i mesi migliori; una campagna mirata su febbraio 2027 può invece trasformare la stagionalità negativa in un’opportunità di crescita.

## Documento Word

In [ ]:
from docx import Document
doc = Document()
doc.add_heading('Report vendite automatico', level=1)
doc.add_paragraph(f"Data di generazione: {datetime.now().strftime('%d/%m/%Y %H:%M')}")

doc.add_heading('Indicatori principali', level=2)
doc.add_paragraph(f"Fatturato totale: {totale:,.2f} euro")
doc.add_paragraph(f"Prodotto più redditizio: {prodotto_top}")
doc.add_paragraph(f"Città con maggior fatturato: {citta_top}")

doc.add_heading('Fatturato per prodotto', level=2)

tabella = doc.add_table(rows=1, cols=2)
tabella.style = 'Table Grid'

intestazione = tabella.rows[0].cells
intestazione[0].text = 'Prodotto'
intestazione[1].text = 'Fatturato'

for _, riga in fatturato_per_prodotto.iterrows():
    celle = tabella.add_row().cells
    celle[0].text = str(riga['prodotto'])
    celle[1].text = f"{riga['fatturato']:,.2f}"

doc.add_heading('Analisi e suggerimenti', level=2)
doc.add_paragraph(
    "L’analisi evidenzia i prodotti e le aree geografiche con maggiore contributo al fatturato. "
    "Si consiglia di monitorare mensilmente l’andamento e di concentrare le attività promozionali "
    "sui segmenti più redditizi."
)

doc.save('report_vendite.docx')

ModuleNotFoundError: No module named 'docx'